# Generated by Django 4.2.3 on 2023-08-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetails",
            name="inv_num",
            field=models.CharField(max_length=200),
        ),
    ]
