# Generated by Django 4.2.3 on 2023-08-08 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_invoicedetails_inv_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicedetails",
            name="business_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
